export default {
  audiobibles: 'audiobibles',
  bibleCDN: 'https://audioverse.org/download/audiobible/',
  new: 'recordings',
  trending: 'recordings/popular',
  featured: 'recordings/featured',
  books: 'audiobooks',
  stories: 'audiobooks?story=1',
  presenters: 'presenters?all=true',
  conferences: 'conferences',
  sponsors: 'sponsors',
  series: 'series',
  topics: 'topics',
  favorites: 'favorite',
  postFavorites: 'favorite',
  deleteFavorites: 'favorite/delete',
  playlists: 'playlist',
  postPlaylists: 'playlist',
  deletePlaylists: 'playlist/0',
  playlistItems: 'playlist',
  postPlaylistItems: 'playlist/recording',
  deletePlaylistItems: 'playlist/recording/0'
}
