# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioVerse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioVerse
  pod 'Firebase/Core', :modular_headers => true

  # When using `cocoapods `to install RN dependencies like `RNReanimated` and so on, developer should also install `React` using `cocoapods`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTActionSheet',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTVibration',
    'RCTPushNotification',
    'RCTCameraRoll',
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'AudioVerseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AudioVerse-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioVerse-tvOS

  target 'AudioVerse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
