declare module '*.png'
declare module '*.json'
declare module 'react-native-render-html'
declare module 'react-native-video-controls'
declare module 'react-navigation-addon-search-layout'
declare module 'redux-mock-store'
declare module 'react-native-dotenv'
declare module 'enzyme-adapter-react-16'
